### ISSUE TITLE
Downloading more recent Ensembl releases E.g: 90

### ISSUE THREAD

**Issue by vmkalbskopf** [openvax/pyensembl#188]
I'd like to use the latest release from Ensemble i.e. release 90, but when I try to specify it, I get

> ValueError: Invalid Ensembl releases 90, must be between 54 and 87

How do I download the most recent version? According to the blog, it is live. I need the new species :-)

**Comment by russ-dvm** [comment]
I was able to install Ensembl Release 90 by modifying MAX_ENSEMBL_RELEASE variable to 90 in "ensembl_release_versions.py"

**Comment by joaoe** [comment]
The current version is at 92.
