### ISSUE TITLE
Crash during install (pyanddoc not installed)

### ISSUE THREAD

**Issue by joaoe** [openvax/pyensembl#199]
Hello !

I'm trying to install `pyensembl` latest and it fails.

```Collecting pyensembl>=1.0.0 (from varcode==0.5.1->-r requirements.txt (line 1))
  Using cached pyensembl-1.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    No module named 'pypandoc'
    Failed to convert %s to reStructuredText README.md
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-szmm6fj4/pyensembl/setup.py", line 86, in <module>
        long_description=readme_restructured,
    NameError: name 'readme_restructured' is not defined
```
Issues:
1. Should be `print("%s" % readme_filename)` https://github.com/openvax/pyensembl/blob/master/setup.py#L40 
2. Then `readme_restructured` might not be defined. https://github.com/openvax/pyensembl/blob/master/setup.py#L86 (would setting it to None work?).
3. You need to specify the `pypandoc` dependency somewhere, preferably before it is used.

Thanks.

**Comment by joaoe** [comment]
Btw, the exact same crash happens with varcode.

**Comment by iskandr** [comment]
Thanks for letting me know @joaoe -- I introduced this bug while mass updating the configs of all the repos we're moving from hammerlab -> openvax. This is fixed in Varcode & others and will be fixed in pyensembl momentarily once I merge https://github.com/openvax/pyensembl/pull/198
