### ISSUE TITLE
Error in returning gene.exons

### ISSUE THREAD

**Issue by abaltsen** [openvax/pyensembl#215]
I am using pyensembl version 1.7.2 for python 3.5.4 to get all exons for a given gene. The error occurs on `return list(sorted(exon_set)) TypeError: unorderable types: Exon() < Exon()`. To reproduce this error, construct a gene object and call on the exons property. I have found that a simple fix of removing sorted(), fixes this error.

**Comment by iskandr** [comment]
Thanks @abaltsen -- should be fixed soon (https://github.com/openvax/pyensembl/pull/216)

**Comment by iskandr** [comment]
OK, sorry for the delay. I just merged #216 and once the tests on the master branch finish, a new version will get uploaded to PyPI.
