### ISSUE TITLE
Potential dependency conflicts between pyensembl and numpy

### ISSUE THREAD

**Issue by NeolithEra** [openvax/pyensembl#237]
Hi, as shown in the following full dependency graph of  **_pyensembl_**, **_pyensembl_** requires _**numpy**_ (>=1.7)， while the installed version of **_gtfparse_**(1.2.0) requires _**numpy>=1.7,<2.0**_.

According to Pip's “first found wins” installation strategy, _**numpy 1.18.2**_ is the actually installed version.  

Although the first found package version _**numpy 1.18.2**_ just satisfies the later dependency constraint （_**numpy>=1.7,<2.0**_), it will lead to a build failure once developers release a newer version of numpy.

### Dependency tree--------
```
pyensembl - 1.8.5
| +- datacache(install version:1.1.5 version range:>=1.1.4)
| | +- appdirs(install version:1.4.3 version range:>=1.4.0)
| | +- mock(install version:4.0.2 version range:*)
| | +- pandas(install version:1.0.3 version range:>=0.15.2)
| | +- progressbar33(install version:2.4 version range:>=2.4)
| | +- requests(install version:2.23.0 version range:>=2.5.1)
| | | +- certifi(install version:2020.4.5.1 version range:>=2017.4.17)
| | | +- chardet(install version:3.0.4 version range:>=3.0.2,<4)
| | | +- idna(install version:2.9 version range:>=2.5,<3)
| | | +- urllib3(install version:1.25.9 version range:>=1.21.1,<1.26)
| | +- typechecks(install version:0.1.0 version range:>=0.0.2)
| +- gtfparse(install version:1.2.0 version range:>=1.1.0)
| | +- numpy(install version:1.18.2 version range:>=1.7,<2.0)
| | +- pandas(install version:1.0.3 version range:>=0.15)
| +- memoized-property(install version:1.0.3 version range:>=1.0.2)
| +- numpy(install version:1.18.2 version range:>=1.7)
| +- pandas(install version:1.0.3 version range:>=0.15)
| +- serializable(install version:0.2.1 version range:*)
| | +- simplejson(install version:3.17.0 version range:*)
| | +- six(install version:1.14.0 version range:>=1.9.0)
| | +- typechecks(install version:0.1.0 version range:>=0.0.2)
| +- six(install version:1.14.0 version range:>=1.9.0)
| +- tinytimer(install version:0.0.0 version range:*)
| +- typechecks(install version:0.1.0 version range:>=0.0.2)
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution
1.	Loosen the version range of **_numpy_** to be **_>=1.7,<=1.18.2_**.
2.	Remove your direct dependency **_numpy_**, and use the **_numpy_** transitively introduced by **_gtfparse_**.


@iskandr Which solution do you prefer, 1 or 2?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by iskandr** [comment]
Thanks @NeolithEra -- Solution #2 seems easiest, a PR would be much appreciated.

**Comment by iskandr** [comment]
Actually, I can just do it quickly.
