### ISSUE TITLE
How to get protein annotation for a input genomic position

### ISSUE THREAD

**Issue by damianosmel** [openvax/pyensembl#244]
Dear developers,

Thank you for creating this tool! I have used it already to automate some refinements of PVS1 evidence criterion, following Tayouen et al. 2018 [work](https://onlinelibrary.wiley.com/doi/full/10.1002/humu.23626?casa_token=cYppWdfyhhcAAAAA%3Av0kvY4bouzyL8NqHv47dZUvWVxur4UnYyLoz4BQONiDT6o6IkSE2Ar8ooQPTjffXr4L5Cy8v9SQe_BBH).

However, there are some steps that I need to know the annotation of the protein (product) for the input variant genomic position. In the [docs](https://pyensembl.readthedocs.io/en/latest/pyensembl.html) there is no explanation for (an available) protein module.

So I would like to ask you, if there is a way on how to retrieve protein feature of a region that is the translation of an input genomic variant position?
If there is such way may you please give a short of an example using pyensembl?

**Comment by LuukHenk** [comment]
Same question here

**Comment by LuukHenk** [comment]
I found a way to access protein sequences using the ensembl_id:
`
data = EnsemblRelease()
data.protein_sequence("ENSEMBLE_ID")
`
So if you can manage to obtain an ensemble_id via a position, a protein sequence can be obtained

**Comment by julia326** [comment]
Hi @damianosmel , sorry for the epic delay on this but glad to hear this tool is useful! We have a related tool for predicting the coding effect of a variant called Varcode, and you can use it like this:

```
from pyensembl import EnsemblRelease
from varcode import Variant

ensembl_grch38 = EnsemblRelease(95, species='human')
Variant(contig=4, start=1807189, ref='C', alt='G', ensembl=ensembl_grch38).effects()
```

Let me know if that doesn't answer your question though.

**Comment by damianosmel** [comment]
> I found a way to access protein sequences using the ensembl_id:
> `data = EnsemblRelease()`
> `protein_ids = data.protein_ids()`
> `data.protein_sequence(protein_ids[0])`

Thank you @LuukHenk! I got similar logic by reading the pyensembl docs.

**Comment by damianosmel** [comment]
> Hi @damianosmel , sorry for the epic delay on this but glad to hear this tool is useful! We have a related tool for predicting the coding effect of a variant called Varcode, and you can use it like this:
> 
> ```
> from pyensembl import EnsemblRelease
> from varcode import Variant
> 
> ensembl_grch38 = EnsemblRelease(95, species='human')
> Variant(contig=4, start=1807189, ref='C', alt='G', ensembl=ensembl_grch38).effects()
> ```
> 
> Let me know if that doesn't answer your question though.

Thank you for detailed answer @julia326. Varcode seems also a very helpful contribution, thanks to all the developers!
To me, by a quick look on its repository, seems as an alternative to VeP or ANNOVAR so I will check out this functionality.

As I have made this issue more like a "how2", I will close this issue. Thank you!
