### ISSUE TITLE
Available assemblies

### ISSUE THREAD

**Issue by DDudka9** [openvax/pyensembl#257]
I am quite intensely using pyensembl (mouse and human) in my molecular evolution analysis (thanks a lot to everyone working on it!). I would like to know if a chimpanzee (or any non-human assembly) will be available in the future. I also have been using the brown rat assembly and it has been working well so far - should I expect it to have more bugs than mouse or human assemblies?

Thank you for working on pyensembl,

Damian

**Comment by iskandr** [comment]
Hi Damian, 

Sorry for the two years delayed response -- PyEnsembl supports a subset of the ensembl.org assemblies. Here's the current supported set: 

```

human = Species.register(
    latin_name="homo_sapiens",
    synonyms=["human"],
    reference_assemblies={
        "GRCh38": (76, MAX_ENSEMBL_RELEASE),
        "GRCh37": (55, 75),
        "NCBI36": (54, 54),
    })

mouse = Species.register(
    latin_name="mus_musculus",
    synonyms=["mouse", "house mouse"],
    reference_assemblies={
        "NCBIM37": (54, 67),
        "GRCm38": (68, 102),
        "GRCm39": (103, MAX_ENSEMBL_RELEASE),
    })

dog = Species.register(
    latin_name="canis_familiaris",
    synonyms=["dog"],
    reference_assemblies={"CanFam3.1": (75, MAX_ENSEMBL_RELEASE)})

cat = Species.register(
    latin_name="felis_catus",
    synonyms=["cat"],
    reference_assemblies={
        "Felis_catus_6.2": (75, 90),
        "Felis_catus_8.0": (91, 92),
        "Felis_catus_9.0": (93, MAX_ENSEMBL_RELEASE),
        
        })

chicken = Species.register(
    latin_name="gallus_gallus",
    synonyms=["chicken"],
    reference_assemblies={
        "Galgal4": (75, 85),
        "Gallus_gallus-5.0": (86, MAX_ENSEMBL_RELEASE)})

# Does the black rat (Rattus Rattus) get used for research too?
brown_rat = Species.register(
    latin_name="rattus_norvegicus",
    synonyms=["brown rat", "lab rat", "rat"],
    reference_assemblies={
        "Rnor_5.0": (75, 79),
        "Rnor_6.0": (80, 104),
        "mRatBN7.2": (105, MAX_ENSEMBL_RELEASE)
    })

macaque = Species.register(
    latin_name="macaca_fascicularis",
    synonyms=["macaque", "Crab-eating macaque"],
    reference_assemblies={
        "Macaca_fascicularis_6.0": (103, MAX_ENSEMBL_RELEASE),
    })

green_monkey = Species.register(
    latin_name="chlorocebus_sabaeus",
    synonyms=["green_monkey", "african_green_monkey"],
    reference_assemblies={
        "ChlSab1.1": (86, MAX_ENSEMBL_RELEASE),
    })

rhesus = Species.register(
    latin_name="macaca_mulatta",
    synonyms=["rhesus"],
    reference_assemblies={"Mmul_10": (75, MAX_ENSEMBL_RELEASE)})

rabbit = Species.register(
    latin_name="oryctolagus_cuniculus",
    synonyms=["rabbit"],
    reference_assemblies={"OryCun2.0": (75, MAX_ENSEMBL_RELEASE)})

gerbil = Species.register(
    latin_name="meriones_unguiculatus",
    synonyms=["gerbil"],
    reference_assemblies={"MunDraft-v1.0": (75, MAX_ENSEMBL_RELEASE)})

syrian_hamster = Species.register(
    latin_name="mesocricetus_auratus",
    synonyms=["syrian_hamster"],
    reference_assemblies={"MesAur1.0": (75, MAX_ENSEMBL_RELEASE)})

chinese_hamster = Species.register(
    latin_name="cricetulus_griseus_chok1gshd",
    synonyms=["chinese_hamster"],
    reference_assemblies={"CHOK1GS_HDv1": (75, MAX_ENSEMBL_RELEASE)})

naked_mole_rat = Species.register(
    latin_name="heterocephalus_glaber_female",
    synonyms=["naked_mole_rat"],
    reference_assemblies={"HetGla_female_1.0": (75, MAX_ENSEMBL_RELEASE)})

guinea_pig = Species.register(
    latin_name="cavia_porcellus",
    synonyms=["guinea_pig"],
    reference_assemblies={"Cavpor3.0": (75, MAX_ENSEMBL_RELEASE)})

pig = Species.register(
    latin_name="sus_scrofa",
    synonyms=["pig"],
    reference_assemblies={"Sscrofa11.1": (75, MAX_ENSEMBL_RELEASE)})
```

**Comment by iskandr** [comment]
If you're still interested, btw, I can add chimpanzee!

**Comment by DDudka9** [comment]
Hi Alex,

Thanks for the info about the species. I was actually mostly interested in Drosophila melanogaster. So many researchers work on this model species around the world and I think it would be a great resource for the community.

Best,

Damian

**Comment by iskandr** [comment]
How's this? 

https://github.com/openvax/pyensembl/pull/282/files#diff-fb115395175caaa3bb84deab38ce96cf45e60a4882a2cb34b9d7eaf117819d0dR267

**Comment by DDudka9** [comment]
Hi Alex,

Yes that would work just great!

Thanks,

Damian

**Comment by DDudka9** [comment]
Hi Alex,

I noticed that the new pyensembl release 2.2.8 is only available on pypi. Im actually using it as part of a conda environment (latest conda version is 2.1.0). Would you be able to  update conda too? Im super excited to test out the Drosophila species you added!

Best,

Damian

**Comment by iskandr** [comment]
I actually haven't been adding anything to conda, not sure who the
maintainer is.

Can someone point me to documentation for adding conda to the deploy logic?

**Comment by DDudka9** [comment]
Hi Alex,

I'm contacting you as a frequent pyensembl user, which is part of a molecular evolution pipeline I built (PMID: 37358475). Ensembl is transitioning to the Ensembl Beta website. Could you tell me how that will impact pysensembl or if the annotations available through that new site will also become available via pyensembl?

Thank you so much for maintaining the tool,

Best,

Damian



Damian Dudka
Postdoctoral Fellow
Michael Lampson lab
University of Pennsylvania
Philadelphia, PA, USA
(215)-898-3693
***@***.***
