### ISSUE TITLE
Downloading breaks due to reliance on deprecated numpy feature

### ISSUE THREAD

**Issue by vluzko** [openvax/pyensembl#276]
`pyensembl` relies on the `numpy.typeDict` value, which has been removed since 2021: https://github.com/numpy/numpy/pull/17586

Specifically downloading data with pyensembl uses [datacache](https://github.com/openvax/datacache), which uses `numpy.typeDict` in [database_types](https://github.com/openvax/datacache/blob/master/datacache/database_types.py)

Error generated by `pyensembl install --release 108 --species human`.

**Comment by iskandr** [comment]
Hey Vincent,

Thanks for letting me know. I just put up datacache 1.2.0 which doesn't use
typeDict anymore, hopefully this fixes the problem.

--Alex
