### ISSUE TITLE
Bump MAX_ENSEMBL_RELEASE to 110?

### ISSUE THREAD

**Issue by jared-maguire** [openvax/pyensembl#287]
This is a wonderful package, and I use it all the time. Thank you so much for writing and maintaining it!

Ensembl version 110 is out; can we bump `MAX_ENSEMBL_RELEASE` accordingly?

Many many thanks in advance. Cheers!

**Comment by iskandr** [comment]
Will be part of this PR: https://github.com/openvax/pyensembl/pull/290
