### ISSUE TITLE
[New feature] Switching from argparse to click

### ISSUE THREAD

**Issue by akmazian** [openvax/pyensembl#304]
Just a random thought, but is it feasible to convert the cli from `argparse` to `click`?
- Rationale
  - Makes code more readable!
  - Allows for a more "prompt-ful" interaction

**Comment by iskandr** [comment]
My plan is to eventually move the OpenVax shell commands to have typed entry functions and use https://github.com/anntzer/defopt for the CLI. Curious to hear your rationale for click instead.
