### ISSUE TITLE
Querying transcript_by_id doesn't work for some releases

### ISSUE THREAD

**Issue by tavinathanson** [openvax/pyensembl#33]
For example for release 49, when I run `data.transcript_by_id('ENST00000001146')` I get:

```
/Users/tavi/drive/work/repos/cancer/pyensembl/pyensembl/database.py in run_sql_query(self, sql, required, query_params)
    253         print sql
    254         print query_params
--> 255         cursor = self.connection.execute(sql, query_params)
    256         results = cursor.fetchall()
    257         if required and len(results) == 0:

OperationalError: no such column: transcript_biotype
```

I assume that this shouldn't error in this way, and instead not query on `transcript_biotype` for older releases that don't have it?

**Comment by iskandr** [comment]
Did you add those print statements?

Also, what does the query look like?

I'm wondering whether supporting version of Ensembl which predate
transcript_biotype might not be worth it. It's a pretty fundamental
concept: what does this transcript do?

**Comment by tavinathanson** [comment]
Yeah, those are my print statements.

I don't think that's even a transcript present in that release: I think it was erroring with that message regardless of transcript ID.

I think it's a good idea to not support Ensembl releases that are too old, as I think it's more important to have very solid code that supports recent releases vs. conditional-filled code that supports a lot more.

**Comment by iskandr** [comment]
Abandoning support for hg18 releases.
