### ISSUE TITLE
Allow a custom cache directory

### ISSUE THREAD

**Issue by tavinathanson** [openvax/pyensembl#96]
`datacache`'s `envkey` functionality should be surfaced to `pyensembl` so that users can customize the cache directory.

See https://github.com/hammerlab/varcode/issues/98

**Comment by kippakers** [comment]
+1 for this request.  My home directory is capped at 10GB.

**Comment by iskandr** [comment]
@tavinathanson Should we add a `pyensembl` command like `pyensembl set-cache-dir`?

**Comment by tavinathanson** [comment]
@iskandr A separate command seems unnecessary; why not just let users set a `PYENSEMBL_CACHE_DIRECTORY` environment variable?

**Comment by kippakers** [comment]
Both would work in my opinion. I'd say that permanently setting environmental variables is a step above running a command in difficulty/confusion potential for entry level bioinformatics people.

**Comment by iskandr** [comment]
Made some progress in this direction with https://github.com/hammerlab/pyensembl/pull/127 and https://github.com/hammerlab/datacache/pull/27, now need to actually expose this to the user.

**Comment by willgdjones** [comment]
Did this die out? Would be very useful for me.

**Comment by 0xaf1f** [comment]
This issue should probably be closed, since you can apparently set `PYENSEMBL_CACHE_DIR` to change your cache location. See https://github.com/hammerlab/pyensembl#cache-location
